id: 模板17
name: 血筛核酸产品供货价
file: templates/模板17：血筛核酸产品供货价.docx
category: 血筛核酸
detail_filter:
  condition_groups:
  - conditions:
    - field: CPXF
      operator: '='
      value: '32'
      value_type: bm
    name: CPXF=血筛核酸
  description: ''
table:
  placeholders:
    start: '{{#明细表}}'
    end: '{{/明细表}}'
  columns:
  - name: 序号
    type: auto_number
  - name: SAP代码
    source_field: WLDM
    source_table: UF_HTJGKST_DT1
  - name: 简称
    source_field: XMJC
    source_table: UF_HTJGKST_DT1
  - name: 品名
    source_field: WLMS
    source_table: UF_HTJGKST_DT1
  - name: 包装规格
    source_field: GG
    source_table: UF_HTJGKST_DT1
  - name: 零售价
    source_field: LSJ
    source_table: UF_HTJGKST_DT1
    format:
      type: currency
      decimal_places: 2
  - name: 供货价
    source_field: GHJY
    source_table: UF_HTJGKST_DT1
    format:
      type: currency
      decimal_places: 2
paragraph_placeholders:
  金额单位:
    value: 元
