id: 模板1
name: KHB、科华生物品牌酶免&胶体金产品供货价
file: templates/模板1：KHB、科华生物品牌酶免&胶体金产品供货价.docx
category: 酶免胶体金
match_conditions:
  产品细分:
  - 酶免试剂
  - 胶体金试剂
detail_filter:
  condition_groups:
  - conditions:
    - field: CPXF
      operator: in
      value:
      - '133'
      - '131'
      value_type: bm
    name: CPXF=酶免试剂
  description: 当产品细分为酶免试剂或胶体金试剂时
table:
  placeholders:
    start: '{{#明细表}}'
    end: '{{/明细表}}'
  columns:
  - name: 产品类别
    source_field: CPXF
    source_table: UF_HTJGKST_DT1
    description: 产品细分
  - name: 序号
    type: auto_number
    description: 自动编号
  - name: 物料编码
    source_field: WLDM
    source_table: UF_HTJGKST_DT1
    description: 物料代码
  - name: 简称
    source_field: XMJC
    source_table: UF_HTJGKST_DT1
    description: 项目简称
  - name: 品名
    source_field: WLMS
    source_table: UF_HTJGKST_DT1
    description: 物料描述
  - name: 规格型号
    source_field: GG
    source_table: UF_HTJGKST_DT1
    description: 规格
  - name: 供货价
    source_field: GHJY
    source_table: UF_HTJGKST_DT1
    description: 供货价_元
    format:
      type: currency
      decimal_places: 2
paragraph_placeholders:
  标题:
    value: KHB、科华生物品牌酶免&胶体金产品供货价
  金额单位:
    value: 元
speeches:
- id: 话术1
  name: 新上市通知
  type: fixed
  position: after_table
  content: '新上市的产品价格另行通知。

    '
