id: 模板6.2
name: 卓越生化（肾功和心肌酶）产品价格-集采经销价
file: templates/模板6.2：卓越生化（肾功和心肌酶）产品价格-集采经销价.docx
category: 集采产品
detail_filter:
  condition_groups:
  - conditions:
    - field: CPXF
      operator: '='
      value: 卓越生化试剂
    name: CPXF=卓越生化试剂
  - conditions:
    - field: DJZMC
      operator: in
      value:
      - 卓越生化-毫升-肾功和心肌酶
      - 卓越生化-毫升-肾功和心肌酶-含校准质控
    name: DJZMC=卓越生化-毫升-肾功和心肌酶
  - conditions:
    - field: SFJC
      operator: '='
      value: 1
    name: SFJC=1
  - conditions:
    - field: BNGHJLX
      operator: '='
      value: 集采经销价
    name: BNGHJLX=集采经销价
  description: ''
table:
  placeholders:
    start: '{{#明细表}}'
    end: '{{/明细表}}'
  columns:
  - name: 序号
    type: auto_number
  - name: 产品名称
    source_field: WLMS
    source_table: UF_HTJGKST_DT1
  - name: 供货价
    source_field: GHJY
    source_table: UF_HTJGKST_DT1
    format:
      type: currency
      decimal_places: 2
paragraph_placeholders:
  金额单位:
    value: 元
speeches:
- id: 话术1
  type: fixed
  position: after_table
  content: （待完善）
