id: 模板20
name: 第三方（和光）生化产品供货价
file: 模板20：第三方（和光）生化产品供货价.docx
category: 外购试剂
paragraph_placeholders:
  标题: 第三方（和光）生化产品供货价
  金额单位: 元

detail_filter:
  condition_groups:
  - conditions:
    - field: CPXF_BM
      operator: '='
      value: '102'
    - field: DJZ
      operator: in
      value:
      - '74'
      - '75'
      - '76'

sort_rules:
- name: 产品类别编码
  description: 产品类别编码正序
  field: CPXF_BM
  order: asc

table:
  columns:
  - name: 序号
    type: auto_number
  - name: SAP代码
    source_field: WLDM
    source_table: UF_HTJGKST_DT1
  - name: 类别
    source_field: JYTC_NAME
    source_table: UF_HTJGKST_DT1
  - name: 品名
    source_field: WLMS
    source_table: UF_HTJGKST_DT1
  - name: 包装规格
    source_field: GG
    source_table: UF_HTJGKST_DT1
  - name: 零售价
    source_field: LSJ
    source_table: UF_HTJGKST_DT1
    transform: currency
    params:
      decimals: 2
  - name: 供货价
    source_field: GHJY
    source_table: UF_HTJGKST_DT1
    transform: currency
    params:
      decimals: 2
  placeholders:
    end: '{{/明细表}}'
    start: '{{#明细表}}'
