id: 模板8
name: KHB、科华生物品牌日立008生化产品供货价
file: 模板8：KHB、科华生物品牌日立008生化产品供货价.docx
category: 日立008
detail_filter:
  condition_groups:
  - conditions:
    - field: CPXF_BM
      operator: '='
      value: '23'

    name: CPXF=日立008试剂
  description: ''
table:
  placeholders:
    start: '{{#明细表}}'
    end: '{{/明细表}}'
  columns:
  - name: 序号
    type: auto_number
  - name: 物料编码
    source_field: WLDM
    source_table: UF_HTJGKST_DT1
  - name: 简称
    source_field: XMJC
    source_table: UF_HTJGKST_DT1
  - name: 分类
    source_field: CPXF_NAME
    source_table: UF_HTJGKST_DT1
  - name: 品名
    source_field: WLMS
    source_table: UF_HTJGKST_DT1
  - name: 规格
    source_field: GG
    source_table: UF_HTJGKST_DT1
  - name: 零售价
    source_field: LSJ
    source_table: UF_HTJGKST_DT1
    format:
      type: currency
      decimal_places: 2
  - name: 供货价
    source_field: GHJY
    source_table: UF_HTJGKST_DT1
    format:
      type: currency
      decimal_places: 2
paragraph_placeholders:
  金额单位: 元
