id: 模板12.1
name: 北极星生化试剂（肾功和心肌酶）产品价格-集采中标价
file: 模板12.1：北极星生化试剂（肾功和心肌酶）产品价格-集采中标价.docx
category: 集采产品
detail_filter:
  condition_groups:
  - conditions:
    - field: CPXF_BM
      operator: '='
      value: '24'

    name: CPXF=北极星生化试剂
  - conditions:
    - field: DJZMC
      operator: in
      value:
      - 北极星生化-肾功和心肌酶-含校准质控
      - Polaris生化-肾功和心肌酶
    name: DJZMC=北极星生化-肾功和心肌酶-含校准质控
  - conditions:
    - field: SFJC
      operator: '='
      value: 1
    name: SFJC=1
  - conditions:
    - field: BNGHJLX
      operator: '='
      value: 集采中标价
    name: BNGHJLX=集采中标价
  description: ''
table:
  placeholders:
    start: '{{#明细表}}'
    end: '{{/明细表}}'
  columns:
  - name: 序号
    type: auto_number
  - name: 产品名称
    source_field: WLMS
    source_table: UF_HTJGKST_DT1
  - name: 供货价
    source_field: GHJY
    source_table: UF_HTJGKST_DT1
    format:
      type: currency
      decimal_places: 2
paragraph_placeholders:
  金额单位: 元
speeches:
- id: 话术1
  type: fixed
  position: after_table
  content: （待完善）
