id: 模板5
name: KHB、SKHB、科华生物品牌卓越生化产品供货价
file: 模板5：KHB、SKHB、科华生物品牌卓越生化产品供货价.docx
category: 卓越生化
detail_filter:
  condition_groups:
  - conditions:
    - field: CPXF_BM
      operator: '='
      value: '22'

    name: CPXF=卓越生化试剂
  description: ''
table:
  placeholders:
    start: '{{#明细表}}'
    end: '{{/明细表}}'
  columns:
  - name: 序号
    type: auto_number
  - name: 物料编码
    source_field: WLDM
    source_table: UF_HTJGKST_DT1
  - name: 简称
    source_field: XMJC
    source_table: UF_HTJGKST_DT1
  - name: 品名
    source_field: WLMS
    source_table: UF_HTJGKST_DT1
  - name: 规格
    source_field: GG
    source_table: UF_HTJGKST_DT1
  - name: 零售价
    source_field: LSJ
    source_table: UF_HTJGKST_DT1
    format:
      type: currency
      decimal_places: 2
  - name: 供货价
    source_field: GHJY
    source_table: UF_HTJGKST_DT1
    format:
      type: currency
      decimal_places: 2
paragraph_placeholders:
  金额单位: 元
